repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.2.2'
    hooks:
      - id: poetry-export
        args: [ "-f", "requirements.txt", "--output", "requirements.txt", "--without-hashes" ]
    files: 'poetry.lock'