name: 'PR annotator with ruff'
description: 'Annotate pull requests with ruff linter'
author: 'Enrique Soria'
branding:
  icon: git-pull-request
  color: blue
runs:
  using: "composite"
  steps:
    - run: |
        output=$(python ${{ github.action_path }}/annotate_pr_with_ruff/main.py)
        output="${output//'%'/'%25'}"
        output="${output//$'\n'/'%0A'}"
        output="${output//$'\r'/'%0D'}"
        echo "::set-output name=errors::$output"
      shell: bash
