name: 'PR annotator with ruff'
description: 'Annotate pull requests with ruff linter'
author: 'Enrique Soria'
branding:
  icon: git-pull-request
  color: blue
runs:
  using: "composite"
  steps:
    - run: python ${{ github.action_path }}/annotate_pr_with_ruff/main.py
      shell: bash
